name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CPANEL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan brightholiday.co.uk >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_rsa brigpksi@brightholiday.co.uk << 'EOF'
            cd /home/brigpksi/public_html/testdev

            # OPTIONAL: clear existing files (careful!)
            # rm -rf *

            # Pull code
            if [ ! -d ".git" ]; then
              git clone https://github.com/muhammadmunib987/dailyjob.git .
            else
              git pull origin main
            fi

            # Laravel setup
            composer install --no-dev --optimize-autoloader
            cp .env.example .env
            php artisan key:generate
            php artisan config:cache
            php artisan migrate --force
          EOF
