name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main
      - munib_dev

jobs: 
  deploy-main:
    if: github.ref == 'refs/heads/main'
    name: Deploy to /dailyjobs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Upload to FTP (Main)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/dailyjobs/
          port: 21
          protocol: ftp
          local-dir: ./
          exclude: |
            **/.git*
            **/node_modules/**
            **/vendor/**
            .env
            README.md
            tests/

  deploy-dev:
    if: github.ref == 'refs/heads/munib_dev'
    name: Deploy to /dailyjobs_munib_dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Upload to FTP (Dev)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/dailyjobs_munib_dev/
          port: 21
          protocol: ftp
          local-dir: ./
          exclude: |
            **/.git*
            **/node_modules/**
            **/vendor/**
            .env
            README.md
            tests/
