name: Deploy Laravel to cPanel

on:
  push:
    branches: [ main ]  # Triggers deployment when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3  # Fetches latest code from repository
    
    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.CPANEL_HOST }}  # FTP host (can be domain or shared IP)
        username: ${{ secrets.CPANEL_USERNAME }}  # cPanel username
        password: ${{ secrets.CPANEL_PASSWORD }}  # cPanel password
        server-dir: /home/brigpksi/consultantpanels.allahhootravels.co.uk/demo/  # Destination folder
        exclude: |
          **/.git*
          **/.git*/**
          .env.example
          README.md
          phpunit.xml
